### ISSUE TITLE
No Android susbsystem option in openFyde

### ISSUE THREAD

**Issue by Devnol** [openFyde/overlay-amd64-openfyde_apu#1]
Hello, I am trying to get Android susbsytem working in the openFyde prebuilt image from this repo (r102-r2) and for some reason, while I can enable Android and install gapps fine on the latest FydeOS, when I use openFyde I can't enable Android subsystem in any way and the gApps installer says "this installer is not supported in your version of FydeOS". Is there a way I can get android in openFyde, since I don't want to use FydeOS because I need a google account in my browser?

**Comment by Gater73** [comment]
Theres also no Linux support and the way i found to enable it can't be done because the files are encrypted, so i can't change the shadow file or the grub configuration, might as well just use chrome os flex this version of the OS doesn't seem to get the same love the proprietary version gets from the devs, for the time being i will just use good old linux

**Comment by Damenly** [comment]
YES, openFyde has no Android susbsytem. However, [openfyde_apu](https://github.com/openFyde/overlay-amd64-openfyde_apu) do has Linux support. If you can't start VMs in other linux OSs how can openFyde do it?

**Comment by carrie0105** [comment]
It's a feature.
